apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-app

bases:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  cloud-provider: azure
  region: southeastasia

configMapGenerator:
- name: fastapi-config
  behavior: merge
  literals:
  - CLOUD_PROVIDER=azure
