apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-app

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- service.yaml
- ingress.yaml
- deployment.yaml
- hpa.yaml
- networkpolicy.yaml
- pdb.yaml

labels:
- includeSelectors: true
  pairs:
    managed-by: kustomize
    env: base

commonLabels:
  app.kubernetes.io/name: fastapi-app
  app.kubernetes.io/version: "1.0.0"

commonAnnotations:
  app.kubernetes.io/managed-by: "kustomize"
  app.kubernetes.io/part-of: "fastapi-k8s-lab"
